<div class="common-desc-padding special-request-control">
    <h1 class="text-center special-request-title text-uppercase"><?= $block->escapeHtml(__('Contact us if you have any special request')) ?></h1>
    <div class="row">
        <div class="col-md-12">
            <form class="form special-request"
                action="<?= $block->getBaseUrl().'special/index/save';?>"
                id="inquiry-form"
                method="post"
                data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                data-mage-init='{"validation":{}}'
                >
                <fieldset class="fieldset">
                    <legend class="legend">
                        <p><?= $block->escapeHtml(__('Please, fill in this form to get in touch with us')) ?></p>
                    </legend>
                    <fieldset class="fieldset row">
                        <input type="hidden" name="country_code" id="country_code">
                        <div class="field fname required col-lg-6">
                            <div class="control">
                                <input name="fname" id="fname" placeholder="<?= $block->escapeHtmlAttr(__('Full Name')) ?>" title="<?= $block->escapeHtmlAttr(__('Full Name')) ?>" class="form-control minimum-length-2 maximum-length-20 validate-length" type="text" data-validate="{required:true,'validate-alpha':true}"/>
                            </div>
                        </div>
                        <div class="field mobile required col-lg-6">
                            <div class="control">
                                <input type="tel" name="mobile" id="phone" placeholder="<?= $block->escapeHtmlAttr(__('Mobile Number')) ?>" title="<?= $block->escapeHtmlAttr(__('050 123 4567')) ?>" class="form-control" type="text" data-validate="{required:true, 'validate-number':true}" />
                            </div>
                        </div>
                        <div class="field email required col-lg-6">
                            <div class="control">
                                <input name="email" id="email" placeholder="<?= $block->escapeHtmlAttr(__('Email Address')) ?>" title="<?= $block->escapeHtmlAttr(__('Email Address')) ?>" class="form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
                            </div>
                        </div>
                        <div class="field subject required col-lg-6">
                            <select id="subject" name="subject" class="form-control" data-validate="{required:true}">
                                <option value=""><?= $block->escapeHtml(__('Select Subject')) ?></option>
                                <option value="Product Related Query"><?= $block->escapeHtml(__('Product Related Query')) ?></option>
                                <option value="New Inquiry"><?= $block->escapeHtml(__('New Inquiry')) ?></option>
                                <option value="Contact to Admin"><?= $block->escapeHtml(__('Contact to Admin')) ?></option>
                            </select>
                        </div>
                        <div class="field message required col-lg-12">
                            <div class="control">
                                <textarea name="message" id="message" placeholder="<?= $block->escapeHtmlAttr(__('Message')) ?>" title="<?= $block->escapeHtmlAttr(__('Message')) ?>" class="form-control maximum-length-250  validate-length" cols="5" rows="3" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </fieldset>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary" id="submit_form">
                            <span><?= $block->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "telinput": "",
            "style": "" 
        }
    }
</script>